services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: demo
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    restart: unless-stopped


networks:
  db:
    driver: bridge

volumes:
  db: