services:
  node_exporter:
    container_name: node_exporter
    image: prom/node-exporter:latest
    command: 
      - '--path.rootfs=/host'
    pid: host
    volumes:
      - '/:/host:ro'

  
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - ./grafana_data:/var/lib/grafana